namespace: ansible
name: digital_ocean
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/ansible.digital_ocean.git
documentation: https://github.com/ansible-collection-migration/ansible.digital_ocean/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.digital_ocean
issues: https://github.com/ansible-collection-migration/ansible.digital_ocean/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
